### ISSUE TITLE
API doc failed to run?

### ISSUE THREAD

**Issue by gossi** [gossi/docblock#13]
Hmm @cristianoc72 I would have expected the API documentation (action) to run and deploy to GH pages. Yet didn't do so. Wasn't even triggered. Wanna have a look? Is my key I provided in the environment maybe wrong?

**Comment by cristianoc72** [comment]
@gossi I found the errors and I plan to fix it this evening (on the train to come back home :smile:).
The problems is here https://github.com/gossi/docblock/blob/e54b8ba54118bd9d2f0b68ea55ab1edd686e8a83/.github/workflows/api.yml#L27
we should use version 3

and here https://github.com/gossi/docblock/blob/e54b8ba54118bd9d2f0b68ea55ab1edd686e8a83/.github/workflows/api.yml#L28
we should use `with` syntax.

Could you please create a `gh-pages` branch?

**Comment by gossi** [comment]
cool 👍 I created a `gh-pages` branch :)
