### ISSUE TITLE
Add VarTag::getVariableName() 

### ISSUE THREAD

**Issue by gossi** [gossi/docblock#3]
As `VarTag::getVariable()` returns the variable name with `$` prefixed, this may be the wrong value to be expected from this method. There should be another method `getVariableName()` which returns the blank variable name, without the `$` sign.

**Comment by gossi** [comment]
Rather the opposite is the case, `getVariable()` should return the name, without the `$` sign.

**Comment by cristianoc72** [comment]
Close via #6
